<?php

namespace vivi\mainBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTest($author)
    {
        $qb = $this->createQueryBuilder('a')
                   ->where('a.author = :author')
                   ->setParameter('author', $author)
                   ->orderBy('a.date', 'DESC')
            ;
       $this->joiner($qb) ;  
       $this->whereCurrentDate($qb);
       return $qb
                 ->getQuery()
                 ->getResult()
            ;
    }
    
    public function joiner(QueryBuilder $qb)
    {
        $qb
           ->leftJoin('a.image', 'img')
           ->addSelect('img')
        ;
    }
    
    public function whereCurrentDate(QueryBuilder $qb)
    {
         $qb
                  ->andWhere('a.date BETWEEN :start AND :end')
                  ->setParameter('start', new \DateTime(date('Y').'-01-01'))
                  ->setParameter('end', new \DateTime(date('Y').'-12-31'))
         ;         
    }
}
